name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Pages folder
      run: |
        mkdir -p public
        cp index.html public/index.html

    - name: Deploy to GitHub Pages
      uses: actions/upload-pages-artifact@v1

    - name: Deploy to Pages
      id: pages
      uses: actions/deploy-pages@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
